### ISSUE TITLE
ImportError: No module named settings_factory_unrolledcbsettings

### ISSUE THREAD

**Issue by rlander** [matthewwithanm/django-classbasedsettings#15]
Hello there! 

I'm having trouble running a project under gunicorn. It runs fine with  manage.py runserver, but it breaks when I run gunicorn (Django==1.3.7, cbsettings==1.2.1).

Here's the full traceback:

013-05-20 23:27:00 [942] [INFO] Starting gunicorn 0.17.2
2013-05-20 23:27:00 [942] [INFO] Listening at: http://127.0.0.1:8000 (942)
2013-05-20 23:27:00 [942] [INFO] Using worker: sync
2013-05-20 23:27:00 [946] [INFO] Booting worker with pid: 946
2013-05-20 23:27:01 [946] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/arbiter.py", line 485, in spawn_worker
    worker.init_process()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/base.py", line 103, in wsgi
    self.callable = self.load()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/djangoapp.py", line 133, in load
    return mod.make_command_wsgi_application(self.admin_media_path)
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/django_wsgi.py", line 113, in make_command_wsgi_application
    reload_django_settings()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/django_wsgi.py", line 54, in reload_django_settings
    reload(mod)
ImportError: No module named settings_factory_unrolledcbsettings
Traceback (most recent call last):
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/arbiter.py", line 485, in spawn_worker
    worker.init_process()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/base.py", line 103, in wsgi
    self.callable = self.load()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/djangoapp.py", line 133, in load
    return mod.make_command_wsgi_application(self.admin_media_path)
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/django_wsgi.py", line 113, in make_command_wsgi_application
    reload_django_settings()
  File "/Users/rlander/.virtualenvs/myapp/lib/python2.6/site-packages/gunicorn/app/django_wsgi.py", line 54, in reload_django_settings
    reload(mod)
ImportError: No module named settings_factory_unrolledcbsettings

**Comment by matthewwithanm** [comment]
Thanks for the report, @rlander! Can you check out the develop branch and see if that does it for you?

**Comment by rlander** [comment]
Wonderful, @matthewwithanm it works perfectly! I was just about to update this issue with my ugly workaround, but you beat me to it (with a much nicer solution, btw :)) Thank you!

**Comment by matthewwithanm** [comment]
Awesome (:

I'll push it to PyPI. Thanks again!
