### ISSUE TITLE
Incompatible with Django 1.9

### ISSUE THREAD

**Issue by RevolutionTech** [matthewwithanm/django-classbasedsettings#17]
[Django 1.7 deprecated django.utils.importlib](https://docs.djangoproject.com/en/1.7/releases/1.7/#django-utils-dictconfig-django-utils-importlib) and Django 1.9 dropped it.

``` python
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    import cbsettings
  File "/home/vagrant/.virtualenvs/flamingo/local/lib/python2.7/site-packages/cbsettings/__init__.py", line 2, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

I'm about to shoot you a pull request.

**Comment by agconti** [comment]
+1

**Comment by RevolutionTech** [comment]
Merged in pull request.
